name: Publish

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  publish:
    name: Publish to PyPI
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up PDM
        uses: pdm-project/setup-pdm@v4
      - name: Build
        run: |
          pdm build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_PASSWORD }}
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
